# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "X.tructure"
repo_name: "agent-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 30

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/agent-arxiv-daily.json'
json_gitpage_path: './docs/agent-arxiv-daily-web.json'
json_wechat_path: './docs/agent-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/README.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Agent":
        filters: ["Agent", "generative agent", "multi-agent"]

# subjects to filter result
subjects: ["cs"]